"""Tests for AST chunker."""

from __future__ import annotations

import pytest

from core.parser.ast_chunker import ASTChunker, CodeChunk
from core.parser.tree_sitter_parser import CodeParser


@pytest.fixture
def chunker() -> ASTChunker:
    """
    Creates and returns a fresh ASTChunker instance for use in pytest tests.

    This pytest fixture provides a new ASTChunker object to test functions, ensuring test isolation by creating a separate instance for each test that requests it.

    Returns:
        ASTChunker: A newly instantiated ASTChunker object ready for testing.

    Example:
        ```
        def test_chunker_functionality(chunker):
            result = chunker.chunk_code(source_code)
        ```
    """
    return ASTChunker()


@pytest.fixture
def parser() -> CodeParser:
    """
    Creates and returns a CodeParser instance for use in pytest test cases.

    This pytest fixture provides a fresh CodeParser instance to test functions, ensuring test isolation by creating a new parser for each test that requests it.

    Returns:
        CodeParser: A new instance of CodeParser for parsing code structures.

    Example:
        ```
        def test_parser_functionality(parser):
            result = parser.parse(source_code)
        ```
    """
    return CodeParser()


def test_chunks_respect_function_boundaries(
    chunker: ASTChunker, parser: CodeParser, sample_py_path: str
) -> None:
    """
    Tests that code chunks generated by the chunker respect function boundaries and contain the expected function name.

    This test verifies that the ASTChunker correctly identifies and chunks code at function boundaries by parsing a sample Python file and checking that the resulting chunks include a function named 'add_numbers' either as a direct chunk name or as part of a chunk name.

    Args:
        chunker (ASTChunker): The AST chunker instance used to split parsed code into chunks.
        parser (CodeParser): The code parser instance used to parse the Python source file.
        sample_py_path (str): The file path to the sample Python file to be parsed and chunked.

    Returns:
        None: This test function does not return a value.

    Raises:
        AssertionError: When no chunks are generated or when 'add_numbers' is not found in any chunk name.

    Example:
        ```
        test_chunks_respect_function_boundaries(chunker, parser, 'tests/fixtures/sample.py')
        ```
    """
    pf = parser.parse_file(sample_py_path)
    chunks = chunker.chunk_file(pf)
    assert len(chunks) > 0
    chunk_names = {c.name for c in chunks}
    assert "add_numbers" in chunk_names or any("add_numbers" in c.name for c in chunks)


def test_never_exceeds_max_tokens(
    chunker: ASTChunker, parser: CodeParser, sample_py_path: str
) -> None:
    """
    Tests that all chunks generated from a parsed file never exceed the maximum token limit.

    This test function validates the chunking mechanism by parsing a Python file, breaking it into chunks, and asserting that each chunk's token count remains at or below the defined MAX_CHUNK_TOKENS threshold.

    Args:
        chunker (ASTChunker): The AST chunker instance used to split the parsed file into chunks.
        parser (CodeParser): The code parser instance used to parse the Python source file.
        sample_py_path (str): The file path to the sample Python file to be parsed and chunked.

    Returns:
        None: This function does not return a value; it performs assertions.

    Raises:
        AssertionError: When any chunk's token count exceeds ASTChunker.MAX_CHUNK_TOKENS.

    Example:
        ```
        test_never_exceeds_max_tokens(chunker, parser, 'path/to/sample.py')
        ```

    Complexity: O(n) time where n is the number of chunks generated, O(1) space
    """
    pf = parser.parse_file(sample_py_path)
    chunks = chunker.chunk_file(pf)
    for chunk in chunks:
        assert chunk.token_count <= ASTChunker.MAX_CHUNK_TOKENS


def test_merges_small_chunks(chunker: ASTChunker) -> None:
    """
    Tests that the ASTChunker merges multiple small code chunks into a single combined chunk.

    This test function verifies that when multiple code chunks with small token counts (below the merging threshold) are passed to the _merge_small_chunks method, they are correctly combined into a single merged chunk containing both function names.

    Args:
        chunker (ASTChunker): An instance of ASTChunker used to test the chunk merging functionality.

    Returns:
        None: This test function does not return a value.

    Example:
        ```
        test_merges_small_chunks(chunker)
        ```
    """
    small1 = CodeChunk(
        chunk_id="a",
        file_path="test.py",
        language="python",
        chunk_type="function",
        name="tiny1",
        source="def tiny1(): pass",
        start_line=0,
        end_line=0,
        token_count=5,
    )
    small2 = CodeChunk(
        chunk_id="b",
        file_path="test.py",
        language="python",
        chunk_type="function",
        name="tiny2",
        source="def tiny2(): pass",
        start_line=1,
        end_line=1,
        token_count=5,
    )
    merged = chunker._merge_small_chunks([small1, small2])
    # Both are small so they should merge
    assert len(merged) == 1
    assert "tiny1" in merged[0].name
    assert "tiny2" in merged[0].name


def test_handles_empty_file(chunker: ASTChunker, parser: CodeParser, tmp_path) -> None:
    """
    Tests that the chunker correctly handles empty Python files by returning an empty list of chunks.

    This test creates an empty Python file, parses it using the CodeParser, processes it through the ASTChunker, and verifies that no chunks are produced from the empty file.

    Args:
        chunker (ASTChunker): The AST chunker instance used to chunk the parsed file into semantic code blocks.
        parser (CodeParser): The code parser instance used to parse the Python source file into a parse tree.
        tmp_path (pathlib.Path): Pytest fixture providing a temporary directory path for creating test files.

    Returns:
        None: This test function does not return a value.

    Example:
        ```
        test_handles_empty_file(chunker, parser, tmp_path)
        ```
    """
    empty_file = tmp_path / "empty.py"
    empty_file.write_text("")
    pf = parser.parse_file(str(empty_file))
    chunks = chunker.chunk_file(pf)
    assert chunks == []


def test_chunk_directory(chunker: ASTChunker, parser: CodeParser, temp_dir_with_py: str) -> None:
    """
    Tests that the ASTChunker can successfully chunk a parsed directory of Python files.

    This test function verifies the chunking functionality by parsing a directory containing Python files and then chunking the parsed results. It asserts that the chunking process produces at least one chunk and that all produced chunks are instances of the CodeChunk class.

    Args:
        chunker (ASTChunker): An instance of ASTChunker used to chunk parsed code into smaller segments.
        parser (CodeParser): An instance of CodeParser used to parse Python files in the directory.
        temp_dir_with_py (str): Path to a temporary directory containing Python files to be parsed and chunked.

    Returns:
        None: This test function does not return a value.

    Example:
        ```
        test_chunk_directory(chunker, parser, '/tmp/test_py_files')
        ```
    """
    parsed = parser.parse_directory(temp_dir_with_py)
    chunks = chunker.chunk_directory(parsed)
    assert len(chunks) > 0
    assert all(isinstance(c, CodeChunk) for c in chunks)
