steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--build-arg"
      - "NEXT_PUBLIC_API_URL=https://api.wrightai.live"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_URL=https://wrightai.live"
      - "--build-arg"
      - "NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_PADDLE_CLIENT_TOKEN=${_NEXT_PUBLIC_PADDLE_CLIENT_TOKEN}"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/wrightai/wrightai/web:${SHORT_SHA}"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/wrightai/wrightai/web:latest"
      - "."

images:
  - "asia-southeast1-docker.pkg.dev/wrightai/wrightai/web:${SHORT_SHA}"
  - "asia-southeast1-docker.pkg.dev/wrightai/wrightai/web:latest"

options:
  logging: CLOUD_LOGGING_ONLY
